// SPDX-FileCopyrightText: Copyright 2025-2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#include "common/elf_info.h"
#include "common/io_file.h"
#include "common/polyfill_thread.h"
#include "common/thread.h"
#include "core/emulator_settings.h"

#include "video_core/cache_storage.h"
#include "video_core/vk_shader_bundle.h"
#include "video_core/renderer_vulkan/vk_instance.h"
#include "video_core/renderer_vulkan/vk_pipeline_cache.h"

#include <miniz.h>

#include <condition_variable>
#include <atomic>
#include <cstdlib>
#include <functional>
#include <future>
#include <mutex>
#include <queue>

namespace {

std::mutex submit_mutex{};
std::atomic<u32> num_requests{};
std::condition_variable_any request_cv{};
std::queue<std::packaged_task<void()>> req_queue{};
std::mutex m_request{};

mz_zip_archive zip_ar{};
bool ar_is_read_only{true};
std::unique_ptr<Storage::ShaderBundle> shader_bundle;

} // namespace

namespace Storage {

void ProcessIO(const std::stop_token& stoken) {
    Common::SetCurrentThreadName("shadPS4:PipelineCacheIO");

    while (true) {
        {
            std::unique_lock lk{submit_mutex};
            Common::CondvarWait(request_cv, lk, stoken, [&] { return num_requests.load(); });
        }

        if (stoken.stop_requested() && !num_requests.load()) {
            break;
        }

        while (num_requests.load()) {
            std::packaged_task<void()> request{};
            {
                std::scoped_lock lock{m_request};
                if (req_queue.empty()) {
                    continue;
                }
                request = std::move(req_queue.front());
                req_queue.pop();
            }

            if (request.valid()) {
                request();
                request.get_future().wait();
            }

            --num_requests;
        }
    }
}

constexpr std::string GetBlobFileExtension(BlobType type) {
    switch (type) {
    case BlobType::ShaderMeta: {
        return "meta";
    }
    case BlobType::ShaderBinary: {
        return "spv";
    }
    case BlobType::PipelineKey: {
        return "key";
    }
    case BlobType::ShaderProfile: {
        return "bin";
    }
    default:
        UNREACHABLE();
    }
}

void DataBase::Open() {
    if (opened) {
        return;
    }

    const auto& game_info = Common::ElfInfo::Instance();

    using namespace Common::FS;
    if (EmulatorSettings.IsPipelineCacheArchived()) {
        mz_zip_zero_struct(&zip_ar);

        cache_path = GetUserPath(PathType::CacheDir) /
                     std::filesystem::path{game_info.GameSerial()}.replace_extension(".zip");

        if (!mz_zip_reader_init_file(&zip_ar, cache_path.string().c_str(),
                                     MZ_ZIP_FLAG_READ_ALLOW_WRITING) ||
            !mz_zip_validate_archive(&zip_ar, 0)) {
            LOG_INFO(Render, "Cache archive {} is not found or archive is corrupted",
                     cache_path.string().c_str());
            mz_zip_reader_end(&zip_ar);
            mz_zip_writer_init_file(&zip_ar, cache_path.string().c_str(), 0);
        }
    } else {
        cache_path = GetUserPath(PathType::CacheDir) / game_info.GameSerial();
        if (!std::filesystem::exists(cache_path)) {
            std::filesystem::create_directories(cache_path);
        }
        // Fingerprint the original package read-only. Vulkan code is generated by
        // the normal runtime compiler, with its actual specialization/state.
        const char* source = std::getenv("BB_SHADER_SOURCE");
        const char* profile = std::getenv("BB_GAME_PROFILE");
        const char* bundle_enabled = std::getenv("BB_SHADER_BUNDLE");
        if (source && profile && std::strcmp(profile,"infamous")==0 &&
            (!bundle_enabled || std::strcmp(bundle_enabled,"0")!=0)) {
            std::error_code ec;
            const auto size=std::filesystem::file_size(source,ec);
            if (!ec && size>=4 && size<=ShaderBundle::Limit) {
                std::vector<u8> data(size);
                std::ifstream input(source,std::ios::binary);
                if (input.read(reinterpret_cast<char*>(data.data()),size) &&
                    std::memcmp(data.data(),"KCAP",4)==0) {
                    const u64 hash=XXH3_64bits(data.data(),data.size());
                    const auto destination=cache_path/"all_shaders.vkpack";
                    const bool existed=std::filesystem::exists(destination,ec);
                    shader_bundle=std::make_unique<ShaderBundle>(destination,hash);
                    const bool loaded=shader_bundle->Load();
                    // One-time migration preserves existing loose cache files.
                    // A mismatching/corrupt package is rebuilt, never filled from
                    // possibly stale loose files belonging to a previous source.
                    if (!existed) for (const auto& entry:std::filesystem::directory_iterator(cache_path)) {
                        const auto ext=entry.path().extension().string();
                        if (ext!=".spv" && ext!=".meta" && ext!=".key" && ext!=".bin") continue;
                        const auto count=entry.file_size(ec);
                        if (ec || count>ShaderBundle::Limit) continue;
                        std::vector<u8> blob(count);
                        std::ifstream file(entry.path(),std::ios::binary);
                        if (file.read(reinterpret_cast<char*>(blob.data()),count))
                            shader_bundle->Put(entry.path().filename().string(),blob);
                    }
                    LOG_INFO(Render,"Runtime Vulkan bundle: source {:x}, {} entries, restored {}",
                             hash,shader_bundle->Snapshot().size(),loaded);
                    shader_bundle->Start();
                }
            }
            if (!shader_bundle) LOG_WARNING(Render,"Shader source unavailable; using loose runtime cache");
        }
    }

    io_worker = std::jthread{ProcessIO};
    opened = true;
}

void DataBase::Close() {
    if (!IsOpened()) {
        return;
    }

    io_worker.request_stop();
    request_cv.notify_all();
    io_worker.join();
    if (shader_bundle) { shader_bundle->Stop(); shader_bundle.reset(); }

    if (EmulatorSettings.IsPipelineCacheArchived()) {
        mz_zip_writer_finalize_archive(&zip_ar);
        mz_zip_writer_end(&zip_ar);
    }

    opened = false;
    LOG_INFO(Render, "Cache dumped");
}

template <typename T>
bool WriteVector(const BlobType type, std::filesystem::path&& path_, std::vector<T>&& v) {
    {
        auto request = std::packaged_task<void()>{[=]() {
            auto path{path_};
            path.replace_extension(GetBlobFileExtension(type));
            if (shader_bundle) {
                if (!shader_bundle->Put(path.filename().string(),std::span{reinterpret_cast<const u8*>(v.data()),v.size()*sizeof(T)}))
                    LOG_WARNING(Render,"Runtime shader bundle capacity exceeded; blob {} not persisted",path.filename().string());
            } else if (EmulatorSettings.IsPipelineCacheArchived()) {
                ASSERT_MSG(!ar_is_read_only,
                           "The archive is read-only. Did you forget to call `FinishPreload`?");
                if (!mz_zip_writer_add_mem(&zip_ar, path.string().c_str(), v.data(),
                                           v.size() * sizeof(T), MZ_BEST_COMPRESSION)) {
                    LOG_ERROR(Render, "Failed to add {} to the archive", path.string().c_str());
                }
            } else {
                using namespace Common::FS;
                // bbport: publish only a closed, complete cache blob. A killed
                // diagnostic run must not expose an empty .key on next boot.
                auto pending = path;
                pending += ".pending";
                {
                    const auto file = IOFile{pending, FileAccessMode::Create};
                    if (file.Write(v) != v.size()) {
                        LOG_ERROR(Render, "Failed to write cache blob {}", path.string());
                        return;
                    }
                }
                if (!MoveFileExW(pending.c_str(),path.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH))
                    LOG_ERROR(Render, "Failed to publish cache blob {}: {}", path.string(), GetLastError());
            }
        }};
        std::scoped_lock lock{m_request};
        req_queue.emplace(std::move(request));
    }

    std::scoped_lock lk{submit_mutex};
    ++num_requests;
    request_cv.notify_one();
    return true;
}

template <typename T>
void LoadVector(BlobType type, std::filesystem::path& path, std::vector<T>& v) {
    using namespace Common::FS;
    path.replace_extension(GetBlobFileExtension(type));
    if (shader_bundle) {
        std::vector<u8> blob;
        if (shader_bundle->Get(path.filename().string(),blob)) {
            if (blob.size()%sizeof(T)) return;
            v.resize(blob.size()/sizeof(T)); std::memcpy(v.data(),blob.data(),blob.size()); return;
        }
        return; // Bundle miss must not resurrect stale loose-file metadata.
    }
    if (EmulatorSettings.IsPipelineCacheArchived()) {
        int index{-1};
        index = mz_zip_reader_locate_file(&zip_ar, path.string().c_str(), nullptr, 0);
        if (index < 0) {
            LOG_WARNING(Render, "File {} is not found in the archive", path.string().c_str());
            return;
        }
        mz_zip_archive_file_stat stat{};
        mz_zip_reader_file_stat(&zip_ar, index, &stat);
        v.resize(stat.m_uncomp_size / sizeof(T));
        mz_zip_reader_extract_to_mem(&zip_ar, index, v.data(), stat.m_uncomp_size, 0);
    } else {
        const auto file = IOFile{path, FileAccessMode::Read};
        v.resize(file.GetSize() / sizeof(T));
        file.Read(v);
    }
}

bool DataBase::Save(BlobType type, const std::string& name, std::vector<u8>&& data) {
    if (!opened) {
        return false;
    }

    auto path = EmulatorSettings.IsPipelineCacheArchived() ? std::filesystem::path{name}
                                                           : cache_path / name;
    return WriteVector(type, std::move(path), std::move(data));
}

bool DataBase::Save(BlobType type, const std::string& name, std::vector<u32>&& data) {
    if (!opened) {
        return false;
    }

    auto path = EmulatorSettings.IsPipelineCacheArchived() ? std::filesystem::path{name}
                                                           : cache_path / name;
    return WriteVector(type, std::move(path), std::move(data));
}

void DataBase::Load(BlobType type, const std::string& name, std::vector<u8>& data) {
    if (!opened) {
        return;
    }

    auto path = EmulatorSettings.IsPipelineCacheArchived() ? std::filesystem::path{name}
                                                           : cache_path / name;
    return LoadVector(type, path, data);
}

void DataBase::Load(BlobType type, const std::string& name, std::vector<u32>& data) {
    if (!opened) {
        return;
    }

    auto path = EmulatorSettings.IsPipelineCacheArchived() ? std::filesystem::path{name}
                                                           : cache_path / name;
    return LoadVector(type, path, data);
}

void DataBase::ForEachBlob(BlobType type, const std::function<void(std::vector<u8>&& data)>& func) {
    const auto& ext = GetBlobFileExtension(type);
    if (shader_bundle) {
        for (auto& [name,data]:shader_bundle->Snapshot()) if (name.ends_with("."+ext)) func(std::move(data));
        return;
    }
    if (EmulatorSettings.IsPipelineCacheArchived()) {
        const auto num_files = mz_zip_reader_get_num_files(&zip_ar);
        for (int index = 0; index < num_files; ++index) {
            std::array<char, MZ_ZIP_MAX_ARCHIVE_FILENAME_SIZE> file_name{};
            file_name.fill(0);
            mz_zip_reader_get_filename(&zip_ar, index, file_name.data(), file_name.size());
            if (std::string{file_name.data()}.ends_with(ext)) {
                mz_zip_archive_file_stat stat{};
                mz_zip_reader_file_stat(&zip_ar, index, &stat);
                std::vector<u8> data(stat.m_uncomp_size);
                mz_zip_reader_extract_to_mem(&zip_ar, index, data.data(), data.size(), 0);
                func(std::move(data));
            }
        }
    } else {
        for (const auto& file_name : std::filesystem::directory_iterator{cache_path}) {
            if (file_name.path().extension().string().ends_with(ext)) {
                using namespace Common::FS;
                const auto& file = IOFile{file_name, FileAccessMode::Read};
                if (file.IsOpen()) {
                    std::vector<u8> data(file.GetSize());
                    file.Read(data);
                    func(std::move(data));
                }
            }
        }
    }
}

void DataBase::Clear() {
    if (!opened || EmulatorSettings.IsPipelineCacheArchived()) {
        return;
    }
    if (shader_bundle) { shader_bundle->Clear(); return; }
    std::error_code ec;
    u64 removed = 0;
    for (const auto& entry : std::filesystem::directory_iterator(cache_path, ec)) {
        if (entry.is_regular_file(ec) && std::filesystem::remove(entry.path(), ec)) {
            ++removed;
        }
    }
    LOG_WARNING(Render, "Pipeline cache cleared ({} files): it is rebuilt for this build", removed);
}

void DataBase::FinishPreload() {
    if (EmulatorSettings.IsPipelineCacheArchived()) {
        mz_zip_writer_init_from_reader(&zip_ar, cache_path.string().c_str());
        ar_is_read_only = false;
    }
}

} // namespace Storage
